[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/views/*"
  to = "/views/:splat"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
